# TheRegiment Docker Compose - Phase 0
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Development volume mount
    networks:
      - regiment-network

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Development volume mount
    depends_on:
      - backend
    networks:
      - regiment-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: theregiment
      POSTGRES_USER: regiment_user
      POSTGRES_PASSWORD: regiment_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  regiment-network:
    driver: bridge 