version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: unless-stopped

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "python", "src/bot/main.py"]
    environment:
      - ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: theregiment
      POSTGRES_USER: regiment_user
      POSTGRES_PASSWORD: regiment_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: theregiment_network 